artipie/docker-adapter

src/main/java/com/artipie/docker/Repo.java, src/main/java/com/artipie/docker/storage/AstoRepo.java, src/test/java/com/artipie/docker/storage/AstoRepoITCase.java
#29 - using `RepoName` in manifest path, added `_manifest` dir to the path, fixed blob path.
=> Fixed manifest path resolution

src/main/java/com/artipie/docker/asto/AstoBlobs.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/main/java/com/artipie/docker/asto/RegistryRoot.java
#41 - save `tmp` blob to storage and delete `tmp` file after complete in `AstoBlob#put`. Added `RepoRoot` base key and reuse it in `AstoRepo` class.
=> Save blob to storage

pom.xml, src/main/java/com/artipie/docker/BlobStore.java, src/main/java/com/artipie/docker/asto/AstoBlobs.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/main/java/com/artipie/docker/misc/BytesFlowAs.java, src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java, src/test/java/com/artipie/docker/asto/AstoDockerTest.java, src/test/java/com/artipie/docker/asto/AstoRepoITCase.java, src/test/java/com/artipie/docker/misc/BytesFlowAsTest.java
#52 - using `ByteBuffer` flow instead of `Byte` flow. Updated ASTO dependency, fixed all interfaces where needed, updated helper objects and adapters.
=> Using bytebuffers instead of bytes

src/main/java/com/artipie/docker/Repo.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
#57 - change signature of `Repo` interface to use `ByteBuffer` for manifest reading.
=> Updated Repo interface

src/main/java/com/artipie/docker/Repo.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
Part of #54 
Repo.manifest() now returns optional result. That is needed, because Docker HTTP API requires to return 404 when manifest is absent in repo
=> #54 - Optional result in Repo.manifest()

src/main/java/com/artipie/docker/http/PullImageManifest.java, src/test/java/com/artipie/docker/http/DockerSlicePullImageManifestTest.java
Part of #54 
Added routing to pull image manifest endpoint, without proper body in response for now.
=> #54 - Routing for pull image manifest endpoint

pom.xml, src/main/java/com/artipie/docker/Tag.java, src/main/java/com/artipie/docker/ref/ManifestRef.java, src/test/java/com/artipie/docker/TagValidTest.java, src/test/java/com/artipie/docker/asto/AstoRepoITCase.java, src/test/java/com/artipie/docker/ref/ManifestRefTest.java
Part of issue #54 
Tag is one of important concepts in Docker API and it's validation is required to implement HTTP API properly.
=> #54 - Added Tag class and it's usage in ManifestRef

pom.xml, src/main/java/com/artipie/docker/http/VersionCheck.java, src/test/java/com/artipie/docker/http/DockerSliceVersionCheckTest.java
Part of #54 
Added "Docker-Distribution-API-Version" header to version check response. It is required for client to know that registry works by 2.0 protocol
=> #54 - Added API version header to version check response

src/main/java/com/artipie/docker/http/DockerSlice.java, src/main/java/com/artipie/docker/http/PullImageManifest.java, src/test/java/com/artipie/docker/http/PullImageManifestGetTest.java
Part of #54 
Pull image manifest endpoint responds with manifest content or 404 if manifest cannot be found
=> #54 - Pull image manifest endpoint responds with manifest content

pom.xml, src/main/java/com/artipie/docker/BlobStore.java, src/main/java/com/artipie/docker/asto/AstoBlobs.java, src/main/java/com/artipie/docker/http/PullLayer.java, src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java, src/test/java/com/artipie/docker/http/PullLayerTest.java
Part of #54
Changed AstoBlobs.blob() method to return no content when it is absent.
Pull layer request returns 404 when content is missing.
=> #54 - Support for absent values when pulling a layer

src/main/java/com/artipie/docker/Repo.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/main/java/com/artipie/docker/http/PullImageManifest.java, src/test/java/com/artipie/docker/asto/AstoRepoITCase.java, src/test/java/com/artipie/docker/http/PullImageManifestGetTest.java
Part of #54 
Response of pull image request now includes Content-Type header as per spec.
`AstoRepo.manifest()` now returns `Manifest`
=> #54 - Added Content-Type header to pull image manifest response

pom.xml, src/main/java/com/artipie/docker/asto/AstoUpload.java, src/test/java/com/artipie/docker/asto/AstoUploadTest.java
Closes #89 
Implemented AstoUpload with support of single chunk. That is enough for stream upload scenario
=> #54 - AstoUpload implementation with support of single chunk

src/main/java/com/artipie/docker/asto/AstoUpload.java, src/test/java/com/artipie/docker/asto/AstoUploadTest.java, src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
Part of #54 
Offset returned in upload status response should be inclusive. Next upload starts at previous offset+1.
=> #54 - Fixed upload offset bug

src/main/java/com/artipie/docker/ref/ManifestRef.java, src/test/java/com/artipie/docker/ref/ManifestRefTest.java
Part of #54 
Added method to represent manifest reference as a string. This is required to generate `Location` header when manifest is added to the registry.
=> #54 - Added ManifestRef.string() method

src/main/java/com/artipie/docker/manifest/JsonManifest.java, src/main/java/com/artipie/docker/manifest/Manifest.java, src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
Part of #54 
Added Manifest.layers() method to read all manifest layer digests. This is required to check their presence when manifest is added.
=> #54 - Added Manifest.layers() method

src/main/java/com/artipie/docker/http/DockerSlice.java, src/main/java/com/artipie/docker/http/ManifestEntity.java, src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java, src/test/java/com/artipie/docker/http/ResponseMatcher.java
For #119 I've implemented manifest head endpoint, extended test and added todo to add `Docker-Content-Digest` to get and head.
=> Head manifest endpoint #119

src/main/java/com/artipie/docker/manifest/JsonManifest.java, src/main/java/com/artipie/docker/manifest/Manifest.java, src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
Part of #54 
Reading config digest from image manifest, that should be used for manifest validation
=> #54 - Reading config digest from manifest

src/main/java/com/artipie/docker/Repo.java, src/main/java/com/artipie/docker/asto/AstoRepo.java
Part of #54
`Repo.layer()` method has no usage and is not expected to be used
=> #54 - Removed unused Repo.layer() method

src/test/java/com/artipie/docker/http/DockerSliceITCase.java
Part of #54
Enabled pull and push integration tests for Linux. Added puzzle for Windows tests.
=> #54 - Integration tests enabled

src/main/java/com/artipie/docker/asto/AstoRepo.java, src/main/java/com/artipie/docker/manifest/JsonManifest.java, src/main/java/com/artipie/docker/manifest/Layer.java, src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
Part of #131 
Reading layer URLs from manifest. These layers are foreign and are not required to be present in blob store when manifest is added
=> #131 - Reading Manifest layer URLs

src/main/java/com/artipie/docker/Repo.java, src/main/java/com/artipie/docker/Upload.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/main/java/com/artipie/docker/asto/AstoUpload.java, src/main/java/com/artipie/docker/http/DockerSlice.java, src/main/java/com/artipie/docker/http/UploadEntity.java
Part of #136 
Added `Repo.startUpload()` method to encapsulate upload start logic. Result is async so writing is storage will be simple to add later.
=> #136 - Moved upload start logic to Repo.startUpload method

src/main/java/com/artipie/docker/asto/AstoRepo.java, src/main/java/com/artipie/docker/manifest/JsonManifest.java, src/main/java/com/artipie/docker/manifest/Manifest.java, src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
Part of #128 
Added `Manifest.digest()` method so digest could be read from manifest instance in slice
=> #128 - Added Manifest.digest() method

src/main/java/com/artipie/docker/asto/AstoRepo.java, src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
Part of #131 
Added foreign layers validation support to AstoRepo. This kind of layers is used in Windows images.
=> #131 - Foreign layers validation in AstoRepo

src/main/java/com/artipie/docker/http/ManifestEntity.java, src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java, src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java, src/test/java/com/artipie/docker/http/ResponseMatcher.java
Closes #128 
Added Docker-Content-Digest header to manifest GET and HEAD responses
=> #128 - Added Docker-Content-Digest header to manifest responses

src/main/java/com/artipie/docker/asto/AstoUpload.java, src/main/java/com/artipie/docker/asto/UploadKey.java, src/test/java/com/artipie/docker/asto/UploadKeyTest.java
Part of #136 
Added `UploadKey` class which represents path to blob upload root. It is required to construct this key outside of `AstoUpload` class to check if upload exists.
=> #136 - Extracted UploadKey

src/main/java/com/artipie/docker/BlobStore.java, src/main/java/com/artipie/docker/asto/AstoBlobs.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/main/java/com/artipie/docker/http/UploadEntity.java, src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java, src/test/java/com/artipie/docker/asto/AstoRepoITCase.java, src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
For #175 I've added `digest` parameter `BlobStore#put` method and got rid of calculating digest twice.
=> #175 - calc digest once on blob put

src/main/java/com/artipie/docker/misc/ByteBufPublisher.java, src/test/java/com/artipie/docker/asto/AstoRepoITCase.java, src/test/java/com/artipie/docker/asto/AstoUploadTest.java, src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
For #182 I've replaced all `Concatenation` usages with `ByteBufPublisher`.
=> #182 - replace Concatenation usages with ByteBufPublisher

src/main/java/com/artipie/docker/Layers.java, src/main/java/com/artipie/docker/asto/AstoLayers.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/test/java/com/artipie/docker/asto/AstoLayersTest.java, src/test/java/com/artipie/docker/asto/AstoRepoTest.java
Part of #167 
Added `Layers` to `Repo` and `AstoLayers` implementation simply delegating all calls to `AstoBlobs`.
This is needed to remove direct access to `BlobStore` from slices.
=> #167 - Added Layers to Repo

src/main/java/com/artipie/docker/http/BlobEntity.java, src/main/java/com/artipie/docker/http/UploadEntity.java
Part of #167 
Reading and writing layers using `Repo.layers()` in HTTP slices instead of `BlobStore`
=> #167 - Accessing layers from HTTP slices via Repo.layers

src/main/java/com/artipie/docker/Blob.java, src/main/java/com/artipie/docker/Docker.java, src/main/java/com/artipie/docker/asto/AstoBlobs.java, src/main/java/com/artipie/docker/asto/AstoDocker.java, src/main/java/com/artipie/docker/asto/AstoLayers.java, src/main/java/com/artipie/docker/asto/AstoManifests.java, src/main/java/com/artipie/docker/asto/AstoRepo.java, src/main/java/com/artipie/docker/asto/BlobStore.java, src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java, src/test/java/com/artipie/docker/asto/AstoDockerTest.java, src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
Closes #167 
Removed BlobStore from Docker, moved the interface to `asto` package, because it is only used there
=> #167 - Removed BlobStore from Docker

src/main/java/com/artipie/docker/http/UploadEntity.java, src/test/java/com/artipie/docker/http/UploadEntityRequestTest.java
Part of #189 - I've updated regexp in `UploadEntity` to support multipart names and added tests.
=> #189 - multipart name in UploadEntity

src/main/java/com/artipie/docker/http/UploadEntity.java, src/test/java/com/artipie/docker/http/UploadEntityRequestTest.java
Closes #206 
Simplified UploadEntity.PATH pattern, so it runs fast and still matches expected strings
=> #206 - Fixed performance issue with UploadEntity.PATH RegEx

src/main/java/com/artipie/docker/proxy/ManifestPath.java, src/test/java/com/artipie/docker/proxy/ManifestPathTest.java
Part of #170
Added ManifestPath representing HTTP path to manifest by repo name and reference in remote Docker registry
=> #170 - Added ManifestPath for proxy

pom.xml, src/main/java/com/artipie/docker/http/UploadEntity.java, src/test/java/com/artipie/docker/http/UploadBlobS3IT.java, src/test/java/com/artipie/docker/http/UploadBlobS3ITCase.java
Closes #183 
Content read from S3Storage cannot be read twice. This caused issue with compatibility with S3.
=> #183 - Fixed blob uploading to S3 storage

src/test/java/com/artipie/docker/http/ContentLengthTest.java
Part of #170 
Reading ContentLength from Headers. That will be used to read `Content-Length` header value from blob & manifest get responses
=> #170 - Reading ContentLength from Headers

src/main/java/com/artipie/docker/misc/RqByRegex.java, src/test/java/com/artipie/docker/misc/RqByRegexTest.java
Path of #189: `UploadEntity`, `BlobEntity` and `ManifestEntity` have repeating code to match request line by regex. I've introduced class to get rid of code duplications.
=> #189 - request by regex

src/main/java/com/artipie/docker/http/ManifestEntity.java, src/main/java/com/artipie/docker/http/UploadEntity.java, src/test/java/com/artipie/docker/http/ManifestEntityRequestTest.java, src/test/java/com/artipie/docker/http/UploadEntityRequestTest.java
For #189 I've used `RqByRegex` in `UploadEntity`, made `ManifestEntity` work with composite repo names.
=> #189 - composite repo name in ManifestEntity

pom.xml, src/main/java/com/artipie/docker/asto/AstoBlobs.java, src/main/java/com/artipie/docker/asto/AstoManifests.java, src/test/java/com/artipie/docker/http/S3CompatibilityITCase.java
Closes #215 
Fixed S3 compatibility issues with manifest PUT and GET operations.
Fixed issue with `AstoBlobs` class corrupting incoming buffers.
=> #215 - Manifests S3 compatibility issues fixed

src/main/java/com/artipie/docker/http/DigestHeader.java, src/test/java/com/artipie/docker/http/DigestHeaderTest.java
Part of #170 
Reading DigestHeader from headers. Will be used to extract digest of manifest from remote registry response.
=> #170 - Reading DigestHeader from headers

src/main/java/com/artipie/docker/proxy/ProxyBlob.java, src/main/java/com/artipie/docker/proxy/ProxyLayers.java, src/test/java/com/artipie/docker/proxy/ClientSliceIT.java, src/test/java/com/artipie/docker/proxy/ProxyBlobTest.java, src/test/java/com/artipie/docker/proxy/ProxyLayersTest.java
Part of #170 
Added `ProxyBlob.size()` implementation. Size is received in HEAD response before blob creation
=> #170 - ProxyBlob.size() implementation

src/main/java/com/artipie/docker/cache/CacheDocker.java, src/main/java/com/artipie/docker/cache/CacheRepo.java, src/main/java/com/artipie/docker/cache/package-info.java, src/test/java/com/artipie/docker/cache/CacheDockerTest.java, src/test/java/com/artipie/docker/cache/package-info.java
Part of #172
Added `CacheDocker` and `CacheRepo` class without implementation
=> #172 - Added CacheDocker and CacheRepo skeleton

src/main/java/com/artipie/docker/proxy/ProxyManifests.java, src/test/java/com/artipie/docker/proxy/ClientSliceIT.java, src/test/java/com/artipie/docker/proxy/ProxyManifestsTest.java
Closes #231 
Checking HTTP response status in `ProxyManifests.get()`, proper handling of 404 status
=> #231 - Checking response status in ProxyManifests.get()

src/main/java/com/artipie/docker/cache/CacheLayers.java, src/main/java/com/artipie/docker/cache/CacheManifests.java, src/test/java/com/artipie/docker/cache/CacheRepoTest.java
Part of #172 
`CacheRepo` implementation, `CacheLayers` and `CacheManifests` skeletons added without proper implementation
=> #172 - CacheRepo implementation, CacheLayers and CacheManifests skeletons

src/main/java/com/artipie/docker/proxy/TokenResponse.java, src/test/java/com/artipie/docker/proxy/TokenResponseTest.java
Part of #171 
Added class to parse authentication token response and extracting token from it. This is needed for authentication of requests to Docker registry.
=> #171 - Authentication token response parsing

src/test/java/com/artipie/docker/http/BaseEntityGetTest.java, src/test/java/com/artipie/docker/http/BlobEntityGetTest.java, src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java, src/test/java/com/artipie/docker/http/ResponseMatcher.java, src/test/java/com/artipie/docker/http/UploadEntityGetTest.java, src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
Part of #129 - simplified `Matchers.allOf` usages with `ResponseMatcher`
=> #129 - simplify Matchers.allOf

src/main/java/com/artipie/docker/proxy/AuthClientSlice.java, src/test/java/com/artipie/docker/proxy/AuthClientSliceTest.java
Part of #171 
Added `AuthClientSlice` that is expected to wrap `ClientSlice` to add authentication header when needed.
Handling of `WWW-Authenticate` header is not implemented yet.
=> #171 - Added AuthClientSlice without auth implementation

src/main/java/com/artipie/docker/composite/ReadWriteDocker.java, src/main/java/com/artipie/docker/composite/ReadWriteRepo.java, src/main/java/com/artipie/docker/composite/package-info.java, src/test/java/com/artipie/docker/composite/ReadWriteDockerTest.java, src/test/java/com/artipie/docker/composite/package-info.java
Part of #255 
Added `ReadWriteDocker` and `ReadWriteRepo` skeleton as start of support for virtual Docker repository
=> #255 - Added ReadWriteDocker and ReadWriteRepo skeleton

src/main/java/com/artipie/docker/composite/MultiReadDocker.java, src/main/java/com/artipie/docker/composite/MultiReadRepo.java, src/test/java/com/artipie/docker/composite/MultiReadDockerTest.java
Part of #173 
Added `MultiReadDocker` and `MultiReadRepo` skeleton to support multi-remote proxy
=> #173 - Added MultiReadDocker and MultiReadRepo skeleton

src/main/java/com/artipie/docker/proxy/ProxyLayers.java, src/test/java/com/artipie/docker/composite/MultiReadLayersIT.java, src/test/java/com/artipie/docker/proxy/ProxyLayersTest.java
Closes #225 
Response status is properly handled in `ProxyLayers`.
`MultiReadLayersIT` checks that proxy layers work well with `MultiReadLayers` (it was not the case before the fix)
=> #225 - Handling response status in ProxyLayers

src/main/java/com/artipie/docker/http/DockerSlice.java, src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java, src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java, src/test/java/com/artipie/docker/http/UploadEntityPostTest.java, src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Part of #275 
Auth for manifest put & upload write endpoints
=> #275 - Auth for manifest put & upload write endpoints

src/main/java/com/artipie/docker/http/DockerSlice.java, src/test/java/com/artipie/docker/http/BaseEntityGetTest.java, src/test/java/com/artipie/docker/http/BlobEntityGetTest.java, src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java, src/test/java/com/artipie/docker/http/DockerAuthITCase.java, src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java, src/test/java/com/artipie/docker/http/UploadEntityGetTest.java
Closes #275 
Auth for all read endpoints, auth integration tests enabled
=> #275 - Auth for all read endpoints, auth integration tests enabled

pom.xml, src/main/java/com/artipie/docker/error/UnauthorizedError.java, src/main/java/com/artipie/docker/http/DockerAuthSlice.java, src/test/java/com/artipie/docker/http/DockerAuthSliceTest.java
Part of #117 
Adding class `DockerAuthSlice` that adds proper errors body to unauthorized response.
=> #117 - Adding errors body to unauthorized response

src/main/java/com/artipie/docker/http/DockerAuthSlice.java, src/main/java/com/artipie/docker/http/DockerSlice.java, src/test/java/com/artipie/docker/http/BaseEntityGetTest.java, src/test/java/com/artipie/docker/http/BlobEntityGetTest.java, src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java, src/test/java/com/artipie/docker/http/DockerAuthSliceTest.java, src/test/java/com/artipie/docker/http/IsUnauthorizedResponse.java, src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java, src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java, src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java, src/test/java/com/artipie/docker/http/UploadEntityGetTest.java, src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java, src/test/java/com/artipie/docker/http/UploadEntityPostTest.java, src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Closes #117 
Unauthroized error responses contain body in proper JSON format.
=> #117 - Unauthorized error returned properly in all endpoints

src/main/java/com/artipie/docker/http/DockerSlice.java, src/main/java/com/artipie/docker/http/ErrorHandlingSlice.java, src/test/java/com/artipie/docker/http/ErrorHandlingSliceTest.java
Part of #298 
`InvalidRepoNameException` thrown in slices translated to error response using `ErrorHandlingSlice`
=> #298 - Translating InvalidRepoNameException to error responses

pom.xml, src/main/java/com/artipie/docker/http/ErrorHandlingSlice.java, src/test/java/com/artipie/docker/http/ErrorHandlingSliceTest.java
Closes #298 
Added handling of sync exceptions in `ErrorHandlingSlice`
=> #298 - Handling sync exceptions in ErrorHandlingSlice

src/main/java/com/artipie/docker/error/DeniedError.java, src/main/java/com/artipie/docker/http/DockerAuthSlice.java, src/test/java/com/artipie/docker/http/DockerAuthSliceTest.java
For #299 
Adding proper error body for forbidden response in `DockerAuthSlice`.
=> #299 - Proper error body for forbidden response

pom.xml, src/main/java/com/artipie/docker/http/DockerSlice.java, src/test/java/com/artipie/docker/http/BaseEntityGetTest.java, src/test/java/com/artipie/docker/http/BlobEntityGetTest.java, src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java, src/test/java/com/artipie/docker/http/DockerAuthITCase.java, src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java, src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java, src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java, src/test/java/com/artipie/docker/http/TestAuthentication.java, src/test/java/com/artipie/docker/http/UploadEntityGetTest.java, src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java, src/test/java/com/artipie/docker/http/UploadEntityPostTest.java, src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Part of #299 
Changed `TestAuthentication`. One user will have permissions in tests and another one will not.
HTTP upgraded to 0.15.7 to use new `Authentication.Joined` class
=> #299 - Two users in TestAuthentication, HTTP upgraded to 0.15.7

pom.xml, src/test/java/com/artipie/docker/http/DockerAuthITCase.java
Updated http version to `0.16.2`, also bumped ppom and asto.
=> Update http to 0.16.2

pom.xml, src/main/java/com/artipie/docker/http/ErrorHandlingSlice.java, src/main/java/com/artipie/docker/proxy/ProxyLayers.java, src/main/java/com/artipie/docker/proxy/ProxyManifests.java, src/test/java/com/artipie/docker/fake/FaultyGetLayers.java, src/test/java/com/artipie/docker/fake/FaultyGetManifests.java, src/test/java/com/artipie/docker/http/ErrorHandlingSliceTest.java
Part of #341
Using `FailedCompletionStage` instead of `CompletableFuture.failedFuture`
=> #341 - Using FailedCompletionStage

src/main/java/com/artipie/docker/asto/AstoManifests.java, src/main/java/com/artipie/docker/error/InvalidManifestException.java, src/main/java/com/artipie/docker/http/ErrorHandlingSlice.java, src/test/java/com/artipie/docker/asto/AstoManifestsTest.java, src/test/java/com/artipie/docker/http/ErrorHandlingSliceTest.java
Closes #356 
`InvalidManifestException` in case of empty manifest
=> #356 - InvalidManifestException in case of empty manifest

src/main/java/com/artipie/docker/error/UnsupportedError.java, src/main/java/com/artipie/docker/http/ErrorHandlingSlice.java, src/test/java/com/artipie/docker/http/ErrorHandlingSliceTest.java
Closes #300 
`UnsupportedOperationException` handling in `ErrorHandlingSlice`
=> #300 - UnsupportedOperationException handling in ErrorHandlingSlice

src/test/java/com/artipie/docker/http/AuthTest.java
Part of #354 
Auth tests for catalog and tags endpoints
=> #354 - Auth tests for catalog and tags endpoints

src/test/java/com/artipie/docker/http/AuthTest.java, src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java, src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java, src/test/java/com/artipie/docker/http/UploadEntityPostTest.java, src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Part of #353 
Auth tests joined for endpoints requiring write permissions
=> #353 - Auth tests joined for endpoints requiring write permissions

pom.xml, src/test/java/com/artipie/docker/ExampleStorage.java
Closes #385 
`ExampleStorage` makes a copy of reference storage
=> #385 - ExampleStorage makes a copy of reference storage

src/main/java/com/artipie/docker/http/CatalogEntity.java, src/main/java/com/artipie/docker/http/ErrorsResponse.java, src/main/java/com/artipie/docker/http/JsonContentType.java, src/main/java/com/artipie/docker/http/TagsEntity.java, src/test/java/com/artipie/docker/http/DockerAuthSliceTest.java, src/test/java/com/artipie/docker/http/IsErrorsResponse.java, src/test/java/com/artipie/docker/http/JsonContentTypeTest.java
Closes #387 
Added `Content-Type` to error response and extracted `JsonContentType` for all JSON responses
=> #387 - Added Content-Type to error response

src/main/java/com/artipie/docker/Upload.java, src/main/java/com/artipie/docker/asto/AstoUpload.java, src/main/java/com/artipie/docker/http/UploadEntity.java, src/test/java/com/artipie/docker/asto/AstoUploadTest.java
Part of #424 
`Upload` `content` and `delete` methods replaced with `putTo`
=> #424 - Upload content and delete methods replaced with putTo

pom.xml, src/main/java/com/artipie/docker/http/ManifestEntity.java, src/main/java/com/artipie/docker/manifest/JsonManifest.java, src/main/java/com/artipie/docker/manifest/Manifest.java, src/test/java/com/artipie/docker/http/CachingProxyITCase.java, src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java
Closes #443 
`ManifestEntity.Head` should add `Content-Length` header, updated asto, disabled test that should be fixed in #442.
=> #443 - add Content-Length to ManifestEntity.Head

src/main/java/com/artipie/docker/Upload.java, src/main/java/com/artipie/docker/asto/AstoUpload.java, src/main/java/com/artipie/docker/http/UploadEntity.java, src/test/java/com/artipie/docker/asto/AstoUploadTest.java, src/test/java/com/artipie/docker/http/CachingProxyITCase.java, src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Closes #447 - replaced `Publisher`s on upload with `Content` and
specify conent's length from HTTP headers received on upload.
=> Propagate content length of uploads

src/main/java/com/artipie/docker/http/ManifestEntity.java, src/main/java/com/artipie/docker/misc/AcceptHeader.java, src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java, src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java, src/test/java/com/artipie/docker/misc/AcceptHeaderTest.java
Fixes #449 
Added class and corresponding test to parse multi-value Accept header. Used this class in `ManifestEntity`.
=> Parse multi-value Accept header

src/main/java/com/artipie/docker/asto/AstoManifests.java, src/main/java/com/artipie/docker/manifest/JsonManifest.java, src/test/java/com/artipie/docker/asto/AstoManifestsTest.java, src/test/java/com/artipie/docker/http/AuthTest.java, src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java, src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
Closes #446 
`mediaType` field in manifest json is required. I've added corresponding check in validation process on upload, corrected `JsonManifest` to throw `InvalidManifestException` when required fields are absent, fixed tests where necessary.
=> Check manifest `mediaType` field on validation

src/main/java/com/artipie/docker/proxy/ProxyBlob.java, src/test/java/com/artipie/docker/proxy/ProxyBlobTest.java
Per #216 
- Check `status`, throw `ArtipieHttpException` if status is not 200, otherwise return content
=> (#216) - Handle status in ProxyBlob.content
