artipie/docker-adapter

- src/main/java/com/artipie/docker/BlobStore.java
- src/main/java/com/artipie/docker/Link.java
#2 - introduced repo and storage interfaces
> Repo and storage interfaces

- src/main/java/com/artipie/docker/Digest.java
- src/main/java/com/artipie/docker/storage/AstoBlobs.java
- src/main/java/com/artipie/docker/storage/BlobPath.java
- src/main/java/com/artipie/docker/storage/BlobStore.java
- src/main/java/com/artipie/docker/storage/package-info.java
- src/test/java/com/artipie/docker/storage/BlobPathTest.java
- src/test/java/com/artipie/docker/storage/package-info.java
#6 - added blob storage load method to interface, added stub ASTO implementation with todo. Renamed `Link` to `Digest` and created a unit test.
> Blob storage load method

- SPEC.md
- pom.xml
- src/main/java/com/artipie/docker/Repo.java
- src/main/java/com/artipie/docker/manifest/ManifestRef.java
- src/main/java/com/artipie/docker/misc/BytesFlowAs.java
- src/main/java/com/artipie/docker/misc/package-info.java
- src/test/java/com/artipie/docker/manifest/ManifestRefTest.java
- src/test/java/com/artipie/docker/manifest/package-info.java
#12 - added manifest reference class to resolve manifest link path by image tag or by image digest. Added unit tests.
> Manifest reference link

- SPEC.md
- src/main/java/com/artipie/docker/RepoName.java
#13 - created class `RepoName.Valid` who validates repository name by docker registry specification rules. Added todo for unit test.
> Valid repo name

- .gitignore
> #22: ignore IntelliJ IDEA files

- SPEC.md
- pom.xml
- src/main/java/com/artipie/docker/Digest.java
- src/main/java/com/artipie/docker/Repo.java
- src/main/java/com/artipie/docker/manifest/BlobRef.java
- src/main/java/com/artipie/docker/manifest/ManifestRef.java
- src/main/java/com/artipie/docker/manifest/RefPath.java
- src/main/java/com/artipie/docker/misc/BytesFlowAs.java
- src/main/java/com/artipie/docker/storage/AstoRepo.java
#17 - implemented manifest resolution:
- updated asto dependency
- refactored `ManifestRepo` to reuse interface with `BlobRef`
- implemented manifest JSON resolution
- removed todo
> Implemented manifest resolution

- src/main/java/com/artipie/docker/Digest.java
#25 - parse digest from link text, added javadoc and unit test
> Digest from link

- pom.xml
- src/main/java/com/artipie/docker/storage/AstoRepo.java
- src/test/java/com/artipie/docker/storage/AstoRepoITCase.java
#31 - fixed integration test:
- fixed blobs path
- added javax.json impl test dependency
> Fixed integration test

- src/main/java/com/artipie/docker/RepoName.java
- src/test/java/com/artipie/docker/RepoNameTest.java
#19 - added unit test for `RepoName.Valid` implementation
> Repo name test

- src/test/java/com/artipie/docker/misc/BytesFlowAsTest.java
#39 - added unit tests for text and json implementations of bytes flow.
> Unit test for bytes flow

- pom.xml
- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/test/java/com/artipie/docker/storage/AstoBlobsITCase.java
#43 - added integration test for blobs to verify the digest and storage path
> Implemented integration test for blobs

- src/main/java/com/artipie/docker/BlobStore.java
- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/test/java/com/artipie/docker/storage/AstoBlobsITCase.java
#10 - fixed blob method, added integration test to read and write same blob
> Fixed blob method, added test

- .github/workflows/git.yaml
- .github/workflows/maven.yml
> Fixed ci builds

- pom.xml
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/VersionCheck.java
- src/main/java/com/artipie/docker/http/package-info.java
- src/test/java/com/artipie/docker/http/DockerSliceVersionCheckTest.java
- src/test/java/com/artipie/docker/http/package-info.java
Part of #54 
Added base Slice for Docker Registry with simple Version Check endpoint.
> #54 - Added DockerSlice with Version Check

- pom.xml
- src/main/java/com/artipie/docker/BlobStore.java
- src/main/java/com/artipie/docker/Repo.java
- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/misc/BytesFlowAs.java
- src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java
- src/test/java/com/artipie/docker/asto/AstoDockerTest.java
- src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
- src/test/java/com/artipie/docker/misc/BytesFlowAsTest.java
Closes #56 
Upgraded ASTO to 0.16
Replaced FileStorage usage with InMemoryStorage in tests
Enabled tests on Windows
> #56 - Tests on Windows enabled, upgraded to ASTO to 0.16

- src/main/java/com/artipie/docker/Digest.java
- src/main/java/com/artipie/docker/Tag.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/ref/ManifestRef.java
- src/test/java/com/artipie/docker/DigestTest.java
- src/test/java/com/artipie/docker/TagValidTest.java
- src/test/java/com/artipie/docker/ref/ManifestRefTest.java
Part of #54 
Added parsing and of string as reference to docker image manifest
> #54 - Parse manifest reference

- pom.xml
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/PullLayer.java
- src/test/java/com/artipie/docker/ExampleStorage.java
- src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
- src/test/java/com/artipie/docker/http/PullImageManifestGetTest.java
- src/test/java/com/artipie/docker/http/PullImageManifestHeadTest.java
- src/test/java/com/artipie/docker/http/PullLayerTest.java
Part of #54 
Added pull layer API endpoint. Minimal functionality without caching support, `Range` header etc
> #54 - Pull layer API endpoint added

- README.md
- SPEC.md
Made several cosmetic corrections in readme and spec.
> Cosmetic corrections in docs

- pom.xml
- src/test/java/com/artipie/docker/http/DockerSliceITCase.java
- src/test/resources/log4j.properties
Part of #54 
Added integration test that is pulling an image from HTTP repository.
Test is disabled for now, because not all API endpoints are ready.
> #54 - Docker pull integration test

- .github/workflows/maven.yml
- pom.xml
For #76 I've added jacoco plugin, set coverages corresponding with current situation and made jacoco report upload to codecov.
> #76 - test coverage

- src/main/java/com/artipie/docker/manifest/JsonManifest.java
- src/main/java/com/artipie/docker/manifest/Manifest.java
- src/main/java/com/artipie/docker/manifest/package-info.java
- src/main/java/com/artipie/docker/misc/Json.java
- src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
- src/test/java/com/artipie/docker/manifest/package-info.java
Part of #54 
Added Manifest interfaces and JsonManifest implementation with methods to read type and save manifest content.
> #54 - Manifest abstraction added

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/PushImageManifest.java
- src/test/java/com/artipie/docker/http/PushImageManifestTest.java
Part of #54 
Added push image manifest endpoint
> #54 - Push image manifest endpoint added

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/StartUpload.java
- src/test/java/com/artipie/docker/http/IsHeader.java
- src/test/java/com/artipie/docker/http/StartUploadTest.java
Part of #54 
Added start upload endpoint
> #54 - Added start upload endpoint

- src/main/java/com/artipie/docker/http/PullImageManifest.java
- src/main/java/com/artipie/docker/manifest/JsonManifest.java
- src/main/java/com/artipie/docker/manifest/Manifest.java
- src/test/java/com/artipie/docker/http/PullImageManifestGetTest.java
- src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
Part of #54 
Added Manifest conversion feature and it's usage in pull image manifest endpoint
> #54 - Added Manifest.convert() and it's usage in PullImageManifest

- src/test/java/com/artipie/docker/http/DockerSliceITCase.java
Part of #54 
Added integration test for docker push operation.
Disabled for now, because not all functionality is ready yet
> #54 - Added push integration test

- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java
Part of #54 
PullLayer transformed to Blob.Get(), added Blob.Head() route
> #54 - Added blob HEAD route

- src/main/java/com/artipie/docker/Upload.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/asto/AstoUpload.java
- src/test/java/com/artipie/docker/asto/AstoUploadTest.java
Part of #54 
Added blob upload abstraction & AstoUpload placeholder
> #54 - Added Upload abstraction and Repo.upload() method

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/asto/BlobKey.java
- src/test/java/com/artipie/docker/asto/BlobKeyTest.java
Part of #54 
Existing BlobRef class had only part of logic building blob key from digest, other was duplicated in codebase.
> #54 - Replaced BlobRef with BlobKey

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPostTest.java
Part of #54 
Appending content to upload on PATCH method, proper headers in response
> #54 - Upload PATCH endpoint implementation

- src/test/java/com/artipie/docker/http/DockerSliceITCase.java
Part of #54 
Added integration test case for pushing an image that is already in the repository
> #54 - Added integration test for pushing image that already exists

- .pdd
- pom.xml
- src/main/java/com/artipie/docker/http/UploadEntity.java
> #54 - Fix for broken master branch

- src/main/java/com/artipie/docker/Repo.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
Part of #54 
Adding manifest to repository
> #54 - Adding manifest to repo

- pom.xml
- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/main/java/com/artipie/docker/http/ContentLength.java
- src/main/java/com/artipie/docker/http/ContentType.java
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java
Part of #54 
Added implementation for blob HEAD endpoint.
> #54 - Blob HEAD endpoint implementation

- pom.xml
Fixed pom.xml to set proper Java target level which is in fact 11 for this project code
> #54 - Java 11 target for compiler

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/ManifestEntity.java
- src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
Part of #54 
Added manifest PUT endpoint implementation
> #54 - Manifest PUT endpoint implementation

- src/main/java/com/artipie/docker/asto/AstoDocker.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
Part of #54
Refactored AstoRepo to access blobs via BlobStore, not by direct access to Storage instance.
> #54 - AstoRepo refactored to access blobs via BlobStore

- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
Part of #54 
Blob GET response expected to have same headers as HEAD response
> #54 - Added headers required by spec to blob GET response

- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/main/java/com/artipie/docker/http/ManifestEntity.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Part of #54
Added digest validation on upload finish
> #54 - Digest validation on blob upload finish

- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
- src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
Part of #54 
Checking layer blobs exist when manifest is added
> #54 - Checking that layers exist when manifest is added

- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/UploadEntityRequestTest.java
> #99 - Added unit tests for UploadEntity.Request class

- .github/workflows/reports.yml
- pom.xml
> #122 - Using Jacoco plugin configuration from parent pom

- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
- src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
Part of #54 
Check that config blob exists in storage when validating manifest
> #54 - Require config exists when manifest is being added

- SPEC.md
> #73 - Improvements to storage structure description in SPEC.md

- src/main/java/com/artipie/docker/Upload.java
- src/main/java/com/artipie/docker/asto/AstoUpload.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/asto/AstoUploadTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
For #137 added `com.artipie.docker.Upload#delete`, implementation, test and todo to continue.
> Remove upload data #137

- src/test/java/com/artipie/docker/http/DockerSliceITCase.java
Part of #131 
Refactored docker integration tests to use same image. This way there will be single place in code to change the image depending on OS.
> #131 - Refactored docker integration tests to use same image

- src/test/java/com/artipie/docker/http/DockerSliceITCase.java
Closes #131 
Using proper image when tests are run on Windows. Tests on Windows enabled
> #131 - Enabled integration tests on Windows

- src/main/java/com/artipie/docker/Upload.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/asto/AstoUpload.java
- src/test/java/com/artipie/docker/asto/AstoUploadTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPostTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Part of #136 
Added `Upload.start()` method creating initial `data` file with zero content.
> #136 - Added Upload.start() method

- .rultor.yml
Disabled integration tests in rultor
> #131 - Disabled integration tests in rultor

- src/main/java/com/artipie/docker/Repo.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Closes #136 
Checking that blob upload exists on PATCH and PUT, respond with 404 if not found
> #136 - Checking existence of Upload on PATCH and PUT operations

- pom.xml
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/BaseEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPostTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Closes #165 
Added base path parameter to `DockerSlice` so it could be integrated into Artipie
> #165 - Base path support

- src/main/java/com/artipie/docker/Repo.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/http/ManifestEntity.java
- src/test/java/com/artipie/docker/asto/AstoRepoITCase.java
Closes #168 
Manifest added to repo as Content instead of Blob
> #168 - Adding manifest as Content instead of Blob

- src/test/java/com/artipie/docker/http/LargeImageITCase.java
- src/test/resources/large-image/Dockerfile
> Implement large file upload test

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
Closes #183 
AstoBlobs provides size of saved content to ASTO storage, some storages cannot work without it
> #183 - Fixed AstoBlobs to provide size for saved blob

- src/main/java/com/artipie/docker/Manifests.java
- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/http/ManifestEntity.java
- src/test/java/com/artipie/docker/asto/AstoManifestsTest.java
- src/test/java/com/artipie/docker/asto/AstoRepoTest.java
Part of #169 
Extracted `Manifests` from `Repo` and `AstoManifests` from `AstoRepo` as-is.
> #169 - Extracted Manifests from Repo

- src/test/java/com/artipie/docker/http/AbstractDockerITCase.java
- src/test/java/com/artipie/docker/http/DockerSliceITCase.java
- src/test/java/com/artipie/docker/http/LargeImageITCase.java
> move common parts of docker integration tests to parent class

- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
> add upload get endpoint

- pom.xml
- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/test/java/com/artipie/docker/ExampleStorage.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
- src/test/java/com/artipie/docker/http/LargeImageITCase.java
- src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java
Closes #212 
Upgraded asto to 0.22 for compatibility reasons
> #212 - Upgraded asto to 0.22

- src/main/java/com/artipie/docker/proxy/ProxyBlob.java
- src/test/java/com/artipie/docker/proxy/ProxyBlobTest.java
Part of #170 
Added ProxyBlob class that reads blob content from remote repository
> #170 - Added ProxyBlob class

- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/test/java/com/artipie/docker/http/BlobEntityRequestTest.java
Closes #189 and #194. I've used `RqByRegex` in `BlobEntity.Request` and added test for it.
> #189 - composite image name in BlobEntity

- src/main/java/com/artipie/docker/proxy/ProxyLayers.java
- src/test/java/com/artipie/docker/proxy/ProxyLayersTest.java
Part of #170 
Added ProxyLayers class implementing Layers for proxy
> #170 - Added ProxyLayers

- pom.xml
- src/main/java/com/artipie/docker/proxy/ClientSlice.java
- src/test/java/com/artipie/docker/proxy/ClientSliceIT.java
Part of #170 
Added ClientSlice which should server as remote Slice in proxy implementation
> #170 - ClientSlice added

- src/test/java/com/artipie/docker/http/DockerSliceITCase.java
- src/test/java/com/artipie/docker/http/LargeImageITCase.java
- src/test/java/com/artipie/docker/junit/DockerClient.java
- src/test/java/com/artipie/docker/junit/DockerClientExtension.java
- src/test/java/com/artipie/docker/junit/DockerClientSupport.java
- src/test/java/com/artipie/docker/junit/DockerRepository.java
- src/test/java/com/artipie/docker/junit/package-info.java
> JUnit extension for docker IT

- src/test/java/com/artipie/docker/http/DockerSliceITCase.java
- src/test/java/com/artipie/docker/http/LargeImageITCase.java
- src/test/java/com/artipie/docker/junit/DockerClientExtension.java
- src/test/java/com/artipie/docker/junit/DockerRepository.java
Closes #196 
Docker HTTP server has to be started with different back-end in tests, so server creation has to be be configurable and so done manually
> #196 - Manual creation of DockerRepository in tests

- src/main/java/com/artipie/docker/http/DigestHeader.java
- src/main/java/com/artipie/docker/proxy/ProxyManifests.java
- src/test/java/com/artipie/docker/proxy/ClientSliceIT.java
- src/test/java/com/artipie/docker/proxy/ProxyManifestsTest.java
Part of #170 
Added `ProxyManifests` class, implementing `Manifests` interface for proxy
> #170 - Added ProxyManifests

- src/test/java/com/artipie/docker/http/ProxyDockerITCase.java
Part of #170 
Added integration test for pulling image via proxy.
Disabled while Docker proxy is not fully functional.
> #170 - Added integration test for pulling image via proxy

- src/test/java/com/artipie/docker/http/ProxyDockerITCase.java
- src/test/java/com/artipie/docker/proxy/ProxyRepoTest.java
Closes #170 
`ProxyRepo` class implemented, integration test enabled
> #170 - ProxyRepo implemented, integration test enabled

- pom.xml
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/proxy/ClientSlice.java
For #226 I've updated arripie/http and used `RsStatus.ByCode` in `ClientSlice`
> #226 - status code translation logic from HTTP

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/asto/AstoManifests.java
Closes #121: I've simplified `AstoBlobs.put()` method not to use temp file. Also, removed puzzle from this class as it does not seem relevant anymore.
> #121 - no temp files in AstoBlobs

- pom.xml
- src/main/java/com/artipie/docker/cache/CacheLayers.java
- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/test/java/com/artipie/docker/http/CachingProxyITCase.java
Part of #172 
Added target integration test for caching proxy.
> #172 - Added integration test for caching proxy

- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/test/java/com/artipie/docker/cache/CacheManifestsTest.java
Part of #172 
Added `CacheManifests` implementation without memoization of origin results in cache.
> #172 - Added CacheManifests implementation

- src/test/java/com/artipie/docker/http/LargeImageITCase.java
For #153 added test for large image pull.
> #153 - large image pull

- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/main/java/com/artipie/docker/cache/CacheRepo.java
- src/test/java/com/artipie/docker/cache/CacheManifestsTest.java
Part of #172 
Implemented saving to cache in `CacheManifests`
> #172 - Saving to cache in CacheManifests

- src/test/java/com/artipie/docker/http/CachingProxyITCase.java
Closes #172 
Finalized docker caching proxy support, integration test fixed and enabled
> #172 - Docker caching proxy integration test fixed and enabled

- pom.xml
- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/main/java/com/artipie/docker/proxy/ProxyBlob.java
- src/main/java/com/artipie/docker/proxy/ProxyLayers.java
- src/main/java/com/artipie/docker/proxy/ProxyManifests.java
- src/test/java/com/artipie/docker/http/BaseEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java
- src/test/java/com/artipie/docker/http/BlobEntityRequestTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityRequestTest.java
- src/test/java/com/artipie/docker/http/S3CompatibilityITCase.java
- src/test/java/com/artipie/docker/http/UploadEntityGetTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPostTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
- src/test/java/com/artipie/docker/http/UploadEntityRequestTest.java
Part of #171 
Upgraded HTTP to 0.12, usage of default HTTP version feature
> #171 - Upgraded HTTP to 0.12, usage of default HTTP version feature

- pom.xml
Part of #172 
Parent pom upgraded to 0.3.4 to fix release problems
> #172 - Parent pom upgraded to 0.3.4

- src/main/java/com/artipie/docker/proxy/AuthClientSlice.java
- src/main/java/com/artipie/docker/proxy/ClientSlices.java
- src/test/java/com/artipie/docker/proxy/AuthClientSliceIT.java
- src/test/java/com/artipie/docker/proxy/AuthClientSliceTest.java
Part of #171 
Added Bearer authentication support in `AuthClientSlice`
> #171 - Bearer authentication support in AuthClientSlice

- src/test/java/com/artipie/docker/http/CachingProxyITCase.java
Part of #171 
Using `AuthClientSlice` in `CachingProxyITCase`, tests enabled on Linux
> #171 - Using AuthClientSlice in CachingProxyITCase

- src/main/java/com/artipie/docker/proxy/AuthClientSlice.java
- src/main/java/com/artipie/docker/proxy/Credentials.java
- src/test/java/com/artipie/docker/proxy/CredentialsTest.java
Part of #171 
Credentials support in `AuthClientSlice`
> #171 - Credentials support in AuthClientSlice

- src/main/java/com/artipie/docker/Manifests.java
- src/test/java/com/artipie/docker/cache/CacheLayersTest.java
- src/test/java/com/artipie/docker/cache/CacheManifestsTest.java
- src/test/java/com/artipie/docker/fake/EmptyGetLayers.java
- src/test/java/com/artipie/docker/fake/EmptyGetManifests.java
- src/test/java/com/artipie/docker/fake/FaultyGetLayers.java
- src/test/java/com/artipie/docker/fake/FaultyGetManifests.java
- src/test/java/com/artipie/docker/fake/FullGetLayers.java
- src/test/java/com/artipie/docker/fake/FullGetManifests.java
- src/test/java/com/artipie/docker/fake/package-info.java
Part of #171 
Fake Layers and Manifests implementations extracted from cache tests
> #171 - Fake Layers and Manifests extracted from cache tests

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/composite/ReadWriteLayers.java
- src/main/java/com/artipie/docker/composite/ReadWriteManifests.java
- src/test/java/com/artipie/docker/composite/ReadWriteRepoTest.java
Part of #255 
`ReadWriteRepo` implementation that could be used for creating virtual Docker repository
> #255 - ReadWriteRepo implementation

- src/main/java/com/artipie/docker/composite/MultiReadLayers.java
- src/test/java/com/artipie/docker/composite/MultiReadLayersTest.java
Part of #173 
`MultiReadLayers` implementation
> #173 - MultiReadLayers implementation

- src/main/java/com/artipie/docker/composite/MultiReadManifests.java
- src/test/java/com/artipie/docker/composite/MultiReadManifestsTest.java
`MultiReadManifests` implementation
> #173 - MultiReadManifests implementation

- src/test/java/com/artipie/docker/composite/MultiReadRepoTest.java
Part of #173 
Added `MultiReadRepo` implementation
> #173 - MultiReadRepo implementation

- src/main/java/com/artipie/docker/composite/MultiReadDocker.java
- src/test/java/com/artipie/docker/http/CachingProxyITCase.java
Closes #173 
Added `MultiReadDocker` integration test
> #173 - MultiReadDocker integration test

- src/test/java/com/artipie/docker/http/CachingProxyITCase.java
Closes #255 
Added integration test for `ReadWriteDocker`
> #255 - Integration test for ReadWriteDocker

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java
For #157 I've moved digests comparison logic to `AstoBlobs.put()` and added test for it.
> #157 - do not read content twice

- src/test/java/com/artipie/docker/http/CachingProxyITCase.java
- src/test/java/com/artipie/docker/http/Image.java
Part of #275 
Extracted `Image` class and code for selecting an image for tests depending on host OS from `CachingProxyITCase` to use in future tests
> #275 - Extracted Image from CachingProxyITCase

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/BaseEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
- src/test/java/com/artipie/docker/http/UploadEntityGetTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPostTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Closes #262 
Removed base path support
> #262 - Removed base path support

- src/main/java/com/artipie/docker/http/TrimmedDocker.java
- src/test/java/com/artipie/docker/http/TrimmedDockerTest.java
For #263 I've introduced `Docker` implementation to cut prefixes from repo name.
> #263 - TrimmedDocker introduced

- pom.xml
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/DockerAuthITCase.java
- src/test/java/com/artipie/docker/http/TestAuthentication.java
- src/test/java/com/artipie/docker/junit/DockerRepository.java
Part of #275 
Added integration tests for authentication in Docker
> #275 - Authentication integration test

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/DockerAuthITCase.java
- src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java
- src/test/java/com/artipie/docker/http/TestAuthentication.java
Part of #275 
Auth implemented for manifest get endpoint
> #275 - Auth for manifest get endpoint

- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/main/java/com/artipie/docker/http/ManifestEntity.java
- src/main/java/com/artipie/docker/manifest/JsonManifest.java
- src/main/java/com/artipie/docker/manifest/Manifest.java
- src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
Closes #240 
Changed `Manifest` interface to be sync
> #240 - Sync Manifest interface

- src/main/java/com/artipie/docker/error/BlobUnknownError.java
- src/main/java/com/artipie/docker/error/DockerError.java
- src/main/java/com/artipie/docker/error/package-info.java
Part of #117 
Added `Error` interface and `BlobUnknownError` implementation.
> #117 - Added Error interface and BlobUnknownError

- src/main/java/com/artipie/docker/http/ErrorsResponse.java
- src/test/java/com/artipie/docker/http/ErrorsResponseTest.java
Part of #117 
Added `ErrorsResponse` class that represents
> #117 - Error response

- pom.xml
- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/main/java/com/artipie/docker/http/ErrorsResponse.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java
- src/test/java/com/artipie/docker/http/IsErrorsResponse.java
Part of #117 
Correct error response for GET and HEAD blob endpoints when blob is not found.
> #117 - Error response when blob not found by digest

- src/main/java/com/artipie/docker/error/ManifestError.java
- src/main/java/com/artipie/docker/http/ManifestEntity.java
- src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java
Part of #117 
Proper response for manifest not found errors
> #117 - Manifest not found errors

- src/main/java/com/artipie/docker/error/UploadUnknownError.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/UploadEntityGetTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Part of #117
Proper response for blob upload not found errors.
> #117 - Upload not found errors

- src/main/java/com/artipie/docker/proxy/ProxyBlob.java
- src/test/java/com/artipie/docker/proxy/ProxyBlobTest.java
Part of #304 
`ProxyBlob` finishes connection handling when body consumed.
That is required to make `ProxyBlob` compatible with `ClientSlice` from HTTP client module.
> #304 - ProxyBlob finishes connection handling when body consumed

- src/main/java/com/artipie/docker/RepoName.java
- src/main/java/com/artipie/docker/error/InvalidRepoNameException.java
- src/test/java/com/artipie/docker/RepoNameTest.java
Part of #298 
Throwing special `InvalidRepoNameException` exception when repo name is validated to handle it in future.
> #298 - InvalidRepoNameException added

- src/test/java/com/artipie/docker/cache/CacheLayersTest.java
- src/test/java/com/artipie/docker/cache/CacheManifestsTest.java
- src/test/java/com/artipie/docker/composite/MultiReadLayersTest.java
- src/test/java/com/artipie/docker/composite/MultiReadManifestsTest.java
- src/test/java/com/artipie/docker/fake/FakeLayers.java
- src/test/java/com/artipie/docker/fake/FakeManifests.java
For #273 FakeLayers and FakeManifests added.
> 273 FakeLayers and FakeManifests added

- src/main/java/com/artipie/docker/composite/ReadWriteManifests.java
- src/test/java/com/artipie/docker/composite/ReadWriteManifestsTest.java
Closes #268 
Add unit tests for `ReadWriteManifests` class.
> 268 read write manifests test

- src/main/java/com/artipie/docker/composite/ReadWriteLayers.java
- src/test/java/com/artipie/docker/composite/ReadWriteLayersTest.java
Closes #269 
Add unit tests for ReadWriteLayers class.
> #269 - readWriteLayersTest added

- src/test/java/com/artipie/docker/asto/AstoUploadsTest.java
Closes #199 
AstoUploadsTest  was added.
> #199 - AstoUploadsTest added

- src/main/java/com/artipie/docker/Tag.java
- src/main/java/com/artipie/docker/error/InvalidTagNameException.java
- src/main/java/com/artipie/docker/http/ErrorHandlingSlice.java
- src/test/java/com/artipie/docker/TagValidTest.java
- src/test/java/com/artipie/docker/http/ErrorHandlingSliceTest.java
Closes #307  
Add `InvalidTagNameException` and tests for this class in `ErrorHandlingSliceTest`.
> #307 - Add InvalidTagNameException

- src/main/java/com/artipie/docker/http/BaseEntity.java
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/BaseEntityGetTest.java
Closes #321 
No permissions check in `BaseEntity`
> #321 - No permissions check in BaseEntity

- pom.xml
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
- src/test/java/com/artipie/docker/http/UploadEntityGetTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPatchTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPostTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Updated htto to 0.16.1 and used permission actions.
> Updated http to 0.16.1

- pom.xml
- src/main/java/com/artipie/docker/http/BaseEntity.java
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/BaseEntityGetTest.java
Closes #338 
HTTP upgraded to 0.16.5
> #338 - HTTP upgraded to 0.16.5

- .github/workflows/ci-checks.yml
- pom.xml
- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/ExampleStorage.java
- src/test/java/com/artipie/docker/asto/AstoManifestsTest.java
- src/test/java/com/artipie/docker/cache/CacheManifestsTest.java
- src/test/java/com/artipie/docker/http/CachingProxyITCase.java
- src/test/java/com/artipie/docker/http/LargeImageITCase.java
- src/test/java/com/artipie/docker/junit/DockerClientExtension.java
- src/test/java/com/artipie/docker/proxy/ProxyLayersTest.java
- src/test/java/com/artipie/docker/proxy/ProxyManifestsTest.java
Closes #341 
Changed target version to Java 8
> #341 - Changed target version to Java 8

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/test/java/com/artipie/docker/asto/AstoBlobsTest.java
Closes #344 
No blob overwrite in `AstoBlobs`
> #344 - No blob overwrite in AstoBlobs

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/asto/AstoDocker.java
- src/main/java/com/artipie/docker/asto/BlobKey.java
- src/main/java/com/artipie/docker/asto/BlobsLayout.java
- src/main/java/com/artipie/docker/asto/DefaultLayout.java
- src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java
- src/test/java/com/artipie/docker/asto/AstoBlobsTest.java
- src/test/java/com/artipie/docker/asto/AstoLayersTest.java
- src/test/java/com/artipie/docker/asto/AstoManifestsTest.java
- src/test/java/com/artipie/docker/asto/AstoRepoTest.java
- src/test/java/com/artipie/docker/composite/ReadWriteRepoTest.java
- src/test/java/com/artipie/docker/fake/FullGetLayers.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Part of #349 
Added `BlobsLayout` and it's default implementation
> #349 - Added BlobsLayout and it's default implementation

- src/main/java/com/artipie/docker/asto/AstoDocker.java
- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/asto/DefaultLayout.java
- src/main/java/com/artipie/docker/asto/Layout.java
- src/main/java/com/artipie/docker/asto/ManifestsLayout.java
- src/test/java/com/artipie/docker/asto/AstoManifestsTest.java
- src/test/java/com/artipie/docker/composite/ReadWriteRepoTest.java
Part of #349 
Added `Layout`, `ManifestsLayout` and it's default implementation
> #349 - Added Layout, ManifestsLayout and it's default implementation

- src/main/java/com/artipie/docker/asto/AstoRepo.java
- src/main/java/com/artipie/docker/asto/AstoUpload.java
- src/main/java/com/artipie/docker/asto/AstoUploads.java
- src/main/java/com/artipie/docker/asto/Layout.java
- src/main/java/com/artipie/docker/asto/UploadsLayout.java
- src/test/java/com/artipie/docker/asto/AstoUploadTest.java
- src/test/java/com/artipie/docker/asto/AstoUploadsTest.java
- src/test/java/com/artipie/docker/composite/ReadWriteRepoTest.java
Closes #349 
Added `UploadsLayout` and it's default implementation
> #349 - Added UploadsLayout and it's default implementation

- src/main/java/com/artipie/docker/Manifests.java
- src/main/java/com/artipie/docker/Tags.java
- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/main/java/com/artipie/docker/composite/MultiReadManifests.java
- src/main/java/com/artipie/docker/composite/ReadWriteManifests.java
- src/main/java/com/artipie/docker/proxy/ProxyManifests.java
- src/test/java/com/artipie/docker/composite/ReadWriteManifestsTest.java
- src/test/java/com/artipie/docker/fake/EmptyGetManifests.java
- src/test/java/com/artipie/docker/fake/FakeManifests.java
- src/test/java/com/artipie/docker/fake/FullGetManifests.java
Part of #354 
`Tags` abstraction added
> #354 - Tags abstraction added

- src/main/java/com/artipie/docker/Catalog.java
- src/main/java/com/artipie/docker/asto/AstoDocker.java
- src/main/java/com/artipie/docker/cache/CacheDocker.java
- src/main/java/com/artipie/docker/composite/MultiReadDocker.java
- src/main/java/com/artipie/docker/composite/ReadWriteDocker.java
- src/main/java/com/artipie/docker/http/TrimmedDocker.java
- src/main/java/com/artipie/docker/proxy/ProxyDocker.java
- src/test/java/com/artipie/docker/http/TrimmedDockerTest.java
Part of #355 
`Catalog` abstraction added
> #355 - Catalog abstraction added

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/TagsEntity.java
- src/test/java/com/artipie/docker/fake/FullTagsManifests.java
- src/test/java/com/artipie/docker/http/TagsEntityGetTest.java
Part of #354
Tags list endpoint
> #354 - Tags list endpoint

- src/main/java/com/artipie/docker/http/CatalogEntity.java
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/CatalogEntityGetTest.java
Part of #355 
Catalog endpoint
> #355 - Catalog endpoint

- pom.xml
- src/main/java/com/artipie/docker/Docker.java
- src/main/java/com/artipie/docker/asto/AstoDocker.java
- src/main/java/com/artipie/docker/cache/CacheDocker.java
- src/main/java/com/artipie/docker/composite/MultiReadDocker.java
- src/main/java/com/artipie/docker/composite/ReadWriteDocker.java
- src/main/java/com/artipie/docker/http/CatalogEntity.java
- src/main/java/com/artipie/docker/http/TrimmedDocker.java
- src/main/java/com/artipie/docker/proxy/ProxyDocker.java
- src/test/java/com/artipie/docker/http/CatalogEntityGetTest.java
- src/test/java/com/artipie/docker/http/TagsEntityGetTest.java
- src/test/java/com/artipie/docker/http/TrimmedDockerTest.java
Part of #355 
Catalog pagination support
> #355 - Catalog pagination support

- src/main/java/com/artipie/docker/Manifests.java
- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/main/java/com/artipie/docker/composite/MultiReadManifests.java
- src/main/java/com/artipie/docker/composite/ReadWriteManifests.java
- src/main/java/com/artipie/docker/http/TagsEntity.java
- src/main/java/com/artipie/docker/proxy/ProxyManifests.java
- src/test/java/com/artipie/docker/composite/ReadWriteManifestsTest.java
- src/test/java/com/artipie/docker/fake/EmptyGetManifests.java
- src/test/java/com/artipie/docker/fake/FakeManifests.java
- src/test/java/com/artipie/docker/fake/FaultyGetManifests.java
- src/test/java/com/artipie/docker/fake/FullGetManifests.java
- src/test/java/com/artipie/docker/fake/FullTagsManifests.java
- src/test/java/com/artipie/docker/http/TagsEntityGetTest.java
Part of #354 
Tags pagination support
> #354 - Tags pagination support

- src/test/java/com/artipie/docker/http/AuthTest.java
- src/test/java/com/artipie/docker/http/BaseEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityGetTest.java
- src/test/java/com/artipie/docker/http/BlobEntityHeadTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityGetTest.java
- src/test/java/com/artipie/docker/http/ManifestEntityHeadTest.java
- src/test/java/com/artipie/docker/http/UploadEntityGetTest.java
Part of #353 
Auth tests joined for endpoints requiring read permissions
> #353 - Auth tests joined for endpoints requiring read permissions

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/test/java/com/artipie/docker/http/AuthTest.java
- src/test/java/com/artipie/docker/http/DockerAuthITCase.java
- src/test/java/com/artipie/docker/http/TestAuthentication.java
Closes #353 
Customizable auth scheme
> #353 - Customizable auth scheme

- src/main/java/com/artipie/docker/asto/ManifestsLayout.java
- src/test/java/com/artipie/docker/asto/DefaultLayoutTest.java
Part of #373 
Added tags to layout
> #373 - Added tags to layout

- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/asto/AstoTags.java
- src/test/java/com/artipie/docker/asto/AstoManifestsTest.java
> #373 - Added AstoTags

- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/asto/AstoTags.java
- src/test/java/com/artipie/docker/asto/AstoTagsTest.java
Closes #373 
Pagination support in `AstoTags`
> #373 - Pagination support in AstoTags

- src/main/java/com/artipie/docker/asto/DefaultLayout.java
- src/main/java/com/artipie/docker/asto/Layout.java
- src/test/java/com/artipie/docker/asto/DefaultLayoutTest.java
Part of #374 
Added repositories root to layout
> #374 - Added repositories root to layout

- src/main/java/com/artipie/docker/asto/AstoCatalog.java
- src/main/java/com/artipie/docker/asto/AstoDocker.java
- src/main/java/com/artipie/docker/asto/AstoTags.java
- src/main/java/com/artipie/docker/asto/Children.java
- src/test/java/com/artipie/docker/asto/AstoDockerTest.java
Part of #374 
`AstoCatalog` added
> #374 - AstoCatalog added

- src/main/java/com/artipie/docker/asto/AstoCatalog.java
- src/main/java/com/artipie/docker/asto/AstoDocker.java
- src/test/java/com/artipie/docker/asto/AstoCatalogTest.java
Closes #374 
Pagination support in `AstoCatalog`
> #374 - Pagination support in AstoCatalog

- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/UploadEntityRequestTest.java
Part of #390 
Mount blob request parameters parsing
> #390 - Mount blob request parameters parsing

- src/main/java/com/artipie/docker/Layers.java
- src/main/java/com/artipie/docker/asto/AstoLayers.java
- src/main/java/com/artipie/docker/cache/CacheLayers.java
- src/main/java/com/artipie/docker/composite/MultiReadLayers.java
- src/main/java/com/artipie/docker/composite/ReadWriteLayers.java
- src/main/java/com/artipie/docker/proxy/ProxyLayers.java
- src/test/java/com/artipie/docker/composite/ReadWriteLayersTest.java
- src/test/java/com/artipie/docker/fake/EmptyGetLayers.java
- src/test/java/com/artipie/docker/fake/FakeLayers.java
- src/test/java/com/artipie/docker/fake/FaultyGetLayers.java
- src/test/java/com/artipie/docker/fake/FullGetLayers.java
Part of #390 
Added `Layers.mount` method without implementation
> #390 - Added Layers.mount method without implementation

- src/main/java/com/artipie/docker/asto/AstoLayers.java
- src/test/java/com/artipie/docker/asto/AstoLayersTest.java
Closes #394 
Mount implemented in `AstoLayers`
> #394 - Mount implemented in AstoLayers

- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/UploadEntityPostTest.java
Closes #390 
Blob mount endpoint implementation
> #390 - Blob mount endpoint implementation

- src/main/java/com/artipie/docker/error/InvalidDigestException.java
- src/main/java/com/artipie/docker/http/ErrorHandlingSlice.java
- src/test/java/com/artipie/docker/http/ErrorHandlingSliceTest.java
Part of #297 
`InvalidDigestException` added
> #297 - InvalidDigestException added

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java
- src/test/java/com/artipie/docker/http/UploadEntityPutTest.java
Closes #297 
Invalid digest error on blob creation
> #297 - Invalid digest error on blob creation

- src/main/java/com/artipie/docker/proxy/CatalogUri.java
- src/test/java/com/artipie/docker/proxy/CatalogUriTest.java
Part of #376 
Added `CatalogUri` class for building catalog endpoint request URI
> #376 - Added CatalogUri

- src/main/java/com/artipie/docker/proxy/ProxyLayers.java
- src/main/java/com/artipie/docker/proxy/ProxyManifests.java
- src/main/java/com/artipie/docker/proxy/ResponseSink.java
Part of #376 
Extracted `ResponseSink` from `ProxyLayers` and `ProxyManifests`
> #376 - Extracted ResponseSink from ProxyLayers and ProxyManifests

- src/main/java/com/artipie/docker/proxy/ProxyDocker.java
- src/test/java/com/artipie/docker/proxy/ProxyDockerIT.java
- src/test/java/com/artipie/docker/proxy/ProxyDockerTest.java
> #376 - Catalog proxy

- src/main/java/com/artipie/docker/composite/ReadWriteDocker.java
- src/test/java/com/artipie/docker/composite/ReadWriteDockerTest.java
Closes #370 
Catalog implemented in `ReadWriteDocker`
> #370 - Catalog implemented in ReadWriteDocker

- src/main/java/com/artipie/docker/misc/CatalogPage.java
- src/test/java/com/artipie/docker/misc/CatalogPageTest.java
Part of #371 
`CatalogPage` extracted from `AstoCatalog`
> #371 - CatalogPage extracted from AstoCatalog

- src/main/java/com/artipie/docker/misc/ParsedCatalog.java
- src/test/java/com/artipie/docker/misc/ParsedCatalogTest.java
Part of #371 
`ParsedCatalog` added
> #371 - ParsedCatalog added

- src/main/java/com/artipie/docker/manifest/JsonManifest.java
- src/test/java/com/artipie/docker/manifest/JsonManifestTest.java
Closes #405 
Support for manifest conversion to wildcard
> #405 - Support for manifest conversion to wildcard

- src/main/java/com/artipie/docker/composite/MultiReadDocker.java
- src/test/java/com/artipie/docker/composite/MultiReadDockerTest.java
- src/test/java/com/artipie/docker/composite/ReadWriteDockerTest.java
- src/test/java/com/artipie/docker/fake/FakeCatalogDocker.java
Closes #371 
Catalog implemented in `MultiReadDocker`
> #371 - Catalog implemented in MultiReadDocker

- src/main/java/com/artipie/docker/composite/MultiReadDocker.java
- src/main/java/com/artipie/docker/misc/JoinedCatalogSource.java
- src/test/java/com/artipie/docker/misc/JoinedCatalogSourceTest.java
Part of #367 
`JoinedCatalogSource` extracted from `MultiReadDocker`
> #367 - JoinedCatalogSource extracted from MultiReadDocker

- src/main/java/com/artipie/docker/http/TrimmedDocker.java
- src/test/java/com/artipie/docker/http/TrimmedDockerTest.java
Closes #368 
Catalog in `TrimmedDocker`
> #368 - Catalog in TrimmedDocker

- src/main/java/com/artipie/docker/cache/CacheDocker.java
- src/test/java/com/artipie/docker/cache/CacheDockerTest.java
- src/test/java/com/artipie/docker/misc/JoinedCatalogSourceTest.java
Closes #368 
Catalog in `CacheDocker`
> #368 - Catalog in CacheDocker

- src/main/java/com/artipie/docker/proxy/TagsListUri.java
- src/test/java/com/artipie/docker/proxy/TagsListUriTest.java
Part of #375 
Added `TagsListUri`
> #375 - Added TagsListUri

- src/main/java/com/artipie/docker/proxy/ProxyManifests.java
- src/test/java/com/artipie/docker/proxy/ProxyManifestsIT.java
- src/test/java/com/artipie/docker/proxy/ProxyManifestsTest.java
Closes #375 
Tags implemented in `ProxyManifests`
> #375 - Tags implemented in ProxyManifests

- src/main/java/com/artipie/docker/composite/ReadWriteLayers.java
- src/test/java/com/artipie/docker/composite/ReadWriteLayersTest.java
Closes #393 
Mount implemented in `ReadWriteLayers`
> #393 - Mount implemented in ReadWriteLayers

- src/main/java/com/artipie/docker/misc/TagsPage.java
- src/test/java/com/artipie/docker/misc/TagsPageTest.java
Part of #366 
Added `TagsPage`
> #366 - Added TagsPage

- src/main/java/com/artipie/docker/misc/ParsedTags.java
- src/test/java/com/artipie/docker/misc/ParsedTagsTest.java
Part of #366 
Added `ParsedTags`
> #366 - Added ParsedTags

- src/main/java/com/artipie/docker/composite/ReadWriteManifests.java
- src/test/java/com/artipie/docker/composite/ReadWriteManifestsTest.java
Closes #369 
Tags implemented in `ReadWriteManifests`
> #369 - Tags implemented in ReadWriteManifests

- src/main/java/com/artipie/docker/http/Scope.java
- src/test/java/com/artipie/docker/http/ScopeTest.java
Part of #417 
Added authentication `Scope`
> #417 - Added authentication Scope

- src/main/java/com/artipie/docker/misc/JoinedTagsSource.java
- src/test/java/com/artipie/docker/misc/JoinedTagsSourceTest.java
Part of #366 
Added `JoinedTagsSource`
> #366 - Added JoinedTagsSource

- src/main/java/com/artipie/docker/cache/CacheDocker.java
- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/main/java/com/artipie/docker/cache/CacheRepo.java
- src/test/java/com/artipie/docker/cache/CacheManifestsTest.java
- src/test/java/com/artipie/docker/cache/CacheRepoTest.java
Closes #366 
Tags implemented in `CacheManifests`
> #366 - Tags implemented in CacheManifests

- src/main/java/com/artipie/docker/http/Scope.java
- src/test/java/com/artipie/docker/http/ScopeTest.java
Part of #417 
Parsing scope from string
> #417 - Parsing scope from string

- src/main/java/com/artipie/docker/composite/MultiReadDocker.java
- src/main/java/com/artipie/docker/composite/MultiReadManifests.java
- src/main/java/com/artipie/docker/composite/MultiReadRepo.java
- src/test/java/com/artipie/docker/composite/MultiReadManifestsTest.java
- src/test/java/com/artipie/docker/composite/MultiReadRepoTest.java
Closes #372 
Tags implemented in `MultiReadManifests`
> #372 - Tags implemented in MultiReadManifests

- src/main/java/com/artipie/docker/asto/AstoUploads.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/asto/AstoUploadsTest.java
- src/test/java/com/artipie/docker/http/UploadEntityRequestTest.java
Closes #422 
Handling empty UUID
> #422 - Handling empty UUID

- src/main/java/com/artipie/docker/http/Scope.java
- src/test/java/com/artipie/docker/http/ScopeTest.java
Part of #417 
Added registry scope
> #417 - Added registry scope

- src/main/java/com/artipie/docker/http/BaseEntity.java
- src/main/java/com/artipie/docker/http/BlobEntity.java
- src/main/java/com/artipie/docker/http/CatalogEntity.java
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/ManifestEntity.java
- src/main/java/com/artipie/docker/http/TagsEntity.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/AuthTest.java
Closes #417 
Scope authentication used for all endpoints
> #417 - Scope authentication

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/asto/AstoManifests.java
- src/main/java/com/artipie/docker/asto/BlobSource.java
- src/main/java/com/artipie/docker/asto/TrustedBlobSource.java
- src/test/java/com/artipie/docker/asto/AstoManifestsTest.java
Part of #424 
Adding `BlobStore` from `BlobSource`, `TrustedBlobSource` added and used in `AstoManifests`
> #424 - Adding BlobStore from BlobSource

- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/asto/CheckedBlobSource.java
Part of #424 
Extracted `CheckedBlobSource` from `AstoBlobs`
> #424 - Extracted CheckedBlobSource from AstoBlobs

- src/main/java/com/artipie/docker/Layers.java
- src/main/java/com/artipie/docker/asto/AstoBlobs.java
- src/main/java/com/artipie/docker/asto/AstoLayers.java
- src/main/java/com/artipie/docker/asto/BlobStore.java
- src/main/java/com/artipie/docker/cache/CacheLayers.java
- src/main/java/com/artipie/docker/cache/CacheManifests.java
- src/main/java/com/artipie/docker/composite/MultiReadLayers.java
- src/main/java/com/artipie/docker/composite/ReadWriteLayers.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/main/java/com/artipie/docker/proxy/ProxyLayers.java
- src/test/java/com/artipie/docker/asto/AstoBlobsITCase.java
- src/test/java/com/artipie/docker/asto/AstoBlobsTest.java
- src/test/java/com/artipie/docker/asto/AstoLayersTest.java
- src/test/java/com/artipie/docker/composite/ReadWriteLayersTest.java
- src/test/java/com/artipie/docker/fake/EmptyGetLayers.java
- src/test/java/com/artipie/docker/fake/FakeLayers.java
- src/test/java/com/artipie/docker/fake/FaultyGetLayers.java
- src/test/java/com/artipie/docker/fake/FullGetLayers.java
- src/test/java/com/artipie/docker/http/ManifestEntityPutTest.java
- src/test/java/com/artipie/docker/http/UploadEntityPostTest.java
Part of #424 
`Layers` `put` method accepts `BlobSource`
> #424 - Layers put accepts BlobSource

- src/main/java/com/artipie/docker/asto/AstoUpload.java
- src/main/java/com/artipie/docker/asto/CheckedBlobSource.java
- src/main/java/com/artipie/docker/misc/DigestedFlowable.java
- src/test/java/com/artipie/docker/asto/AstoUploadTest.java
Part of #424 
`AstoUpload` moves data instead of read and write
> #424 - AstoUpload moves data instead of read and write

- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/ManifestEntity.java
- src/main/java/com/artipie/docker/http/Scope.java
- src/test/java/com/artipie/docker/http/AuthTest.java
For #434 
Added permission to overwrite tag. Please, note that user with `overwrite` permission can also create new tags.
> #434 - Added permission to overwrite tag

- pom.xml
> #435 - update asto

- README.md
Updated badges in readme to correspond Artipie common format.
> #0 - updated readme badges

- .rultor.yml
Added myself and @genryxy to rultor architects, removed Oleg.
> Added myself to rultor architects

- src/main/java/com/artipie/docker/Upload.java
- src/main/java/com/artipie/docker/asto/AstoUpload.java
- src/main/java/com/artipie/docker/http/DockerSlice.java
- src/main/java/com/artipie/docker/http/UploadEntity.java
- src/test/java/com/artipie/docker/http/UploadEntityDeleteTest.java
> (#138) - Support for canceling upload
